### PR TITLE
Update python dependencies

### PR DESCRIPTION
**Pull request by sgvandijk**
Add missing `stringcase` Python dependency

### CODE REVIEW

**Comment by TrentHouliston** [comment]
This is indeed missing!
Although now that I think about it it might be a good idea to just add a pip requirements.txt file.
Then you could just pip3 install -r requirements.txt.
Would you like to do that or should I?

**Comment by sgvandijk** [comment]
I can do that yeah. Would you prefer separate requirement files for the Python binding and Neutron requirements, or just stick them in one?

**Comment by TrentHouliston** [comment]
All together should be fine thanks!

**Comment by TrentHouliston** [comment]
The pybind stuff requires neutron to work anyway

**Comment by TrentHouliston** [comment]
Thanks!

**Pull request merged**
